### ISSUE TITLE
Admob preload interstitial

### ISSUE THREAD

**Issue by hgokturk** [SonarSystems/Cocos-Helper#43]
I've been waiting for a long long time for preload insterstitial/show preloaded interstitial to be get working by you guys :) It's not working.

**Comment by hgokturk** [comment]
01-20 01:09:26.467: E/AndroidRuntime(18258): FATAL EXCEPTION: main
01-20 01:09:26.467: E/AndroidRuntime(18258): Process: com.dreals.superlototahminprogrami, PID: 18258
01-20 01:09:26.467: E/AndroidRuntime(18258): java.lang.UnsatisfiedLinkError: No implementation found for void sonar.systems.frameworks.AdMob.AdMobAds.FullscreenAdPreloaded(boolean) (tried Java_sonar_systems_frameworks_AdMob_AdMobAds_FullscreenAdPreloaded and Java_sonar_systems_frameworks_AdMob_AdMobAds_FullscreenAdPreloaded__Z)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at sonar.systems.frameworks.AdMob.AdMobAds.FullscreenAdPreloaded(Native Method)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at sonar.systems.frameworks.AdMob.AdMobAds$1.onAdLoaded(AdMobAds.java:116)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at com.google.android.gms.ads.internal.client.zzc.onAdLoaded(Unknown Source)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at com.google.android.gms.ads.internal.client.zzo$zza.onTransact(Unknown Source)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at android.os.Binder.transact(Binder.java:380)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at com.google.android.gms.ads.internal.client.t.c(SourceFile:152)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at com.google.android.gms.ads.internal.a.o(SourceFile:771)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at com.google.android.gms.ads.internal.x.o(SourceFile:386)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at com.google.android.gms.ads.internal.a.b(SourceFile:405)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at com.google.android.gms.ads.internal.b.b(SourceFile:149)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at com.google.android.gms.ads.internal.p.a.a(SourceFile:125)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at com.google.android.gms.ads.internal.p.a.a(SourceFile:91)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at com.google.android.gms.ads.internal.u.c.e(SourceFile:398)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at com.google.android.gms.ads.internal.u.c.onPageFinished(SourceFile:374)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:513)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:188)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at android.os.Handler.dispatchMessage(Handler.java:102)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at android.os.Looper.loop(Looper.java:135)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at android.app.ActivityThread.main(ActivityThread.java:5319)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at java.lang.reflect.Method.invoke(Native Method)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at java.lang.reflect.Method.invoke(Method.java:372)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
01-20 01:09:26.467: E/AndroidRuntime(18258):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by aleksmutlu** [comment]
@hgokturk check this if you want to preload the interstitial, and call it whenever you need.

http://discuss.cocos2d-x.org/t/sonar-cocos-helper-admob-full-add-problem/24941/11

**Comment by codinghaven** [comment]
@hgokturk  I had this problem too, It seems that SonarSystems simply didn't implement the `FullscreenAdPreloaded(bool)` and yet it was used in `onCreate()` of the `AdMobAds.java` class.

Just go to the `AdMobAds.java` search for `FullscreenAdPreloaded(true);` and simply comment that function call, everything should work :)
